### ISSUE TITLE
error in --fastq_stats on MaxOSX 10.8.5

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch#135]
When I run `--fastq_stats` on MaxOSX 10.8.5, I get this error.

It appears to be a "non-Mavericks" issue according to USGS-R/glmtools#80

```
WE2292:fastq-test-suite bris469$ vsearch -fastq_stats misc_rna_original_sanger.fastq
vsearch v1.8.0_osx_x86_64, 8.0GB RAM, 4 cores
https://github.com/torognes/vsearch

Reading fastq file 0%dyld: lazy symbol binding failed: Symbol not found: ___exp10
  Referenced from: /usr/local/bin/vsearch
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___exp10
  Referenced from: /usr/local/bin/vsearch
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

**Comment by torognes** [comment]
Hi @colinbrislawn , is this with the distributed binary or did you compile it yourself?

**Comment by colinbrislawn** [comment]
I got this error using the distributed binary. 

I just tried building from source. I then got this error when running `autogen.sh`. 

```
WE2292:vsearch bris469$ ./autogen.sh 
configure.ac:4: error: Autoconf version 2.63 or higher is required
configure.ac:4: the top level
autom4te: /usr/bin/gm4 failed with exit status: 63
aclocal: /usr/bin/autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
```

I have `autoconf (GNU Autoconf) 2.61` installed and I am now trying to install a newer version.

**Comment by xflouris** [comment]
Hi @colinbrislawn , try changing the third line in configure.ac from `AC_PREREQ([2.63])` to `AC_PREREQ([2.61])`

and try ./autogen.sh once more. I don't think there were critical changes from 2.61 to 2.63 that would break this configuration.

**Comment by colinbrislawn** [comment]
Thanks for the advice! I tried changing it and got a new error. Full log:

```
WE2292:vsearch bris469$ nano configure.ac 
WE2292:vsearch bris469$ 
WE2292:vsearch bris469$ 
WE2292:vsearch bris469$ ./autogen.sh 
configure.ac:81: installing `./compile'
configure.ac:6: installing `./missing'
configure.ac:6: installing `./install-sh'
src/Makefile.am: installing `./depcomp'
WE2292:vsearch bris469$ make
make: *** No targets specified and no makefile found.  Stop.
WE2292:vsearch bris469$ 
WE2292:vsearch bris469$ 
WE2292:vsearch bris469$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking for C++ compiler default output file name... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for ranlib... ranlib
checking for a BSD-compatible install... /usr/bin/install -c
checking for pthread_create in -lpthread... yes
checking for dlopen in -ldl... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking x86intrin.h usability... no
checking x86intrin.h presence... no
checking for x86intrin.h... no
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for inline... inline
checking for size_t... yes
checking for uint32_t... yes
checking for int64_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working strtod... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for memmove... yes
checking for memcpy... yes
checking for posix_memalign... yes
checking for gettimeofday... yes
checking for localtime_r... yes
checking for memchr... yes
checking for memset... yes
checking for pow... yes
checking for regcomp... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strcspn... yes
checking for sysinfo... no
checking for library containing pthread_create... none required
checking for ps2pdf... no
configure: WARNING: *** ps2pdf is required to build a PDF version of the manual
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: creating config.h
config.status: executing depfiles commands
WE2292:vsearch bris469$ make
make  all-recursive
Making all in src
g++ -DHAVE_CONFIG_H -I. -I..    -msse2 -g -O2 -MT libcpu_sse2_a-cpu.o -MD -MP -MF .deps/libcpu_sse2_a-cpu.Tpo -c -o libcpu_sse2_a-cpu.o `test -f 'cpu.cc' || echo './'`cpu.cc
In file included from cpu.cc:61:
vsearch.h:69:23: error: x86intrin.h: No such file or directory
cpu.cc: In function ‘void increment_counters_from_bitmap_sse2(short unsigned int*, unsigned char*, unsigned int)’:
cpu.cc:99: error: ‘__m128i’ does not name a type
cpu.cc:102: error: ‘__m128i’ does not name a type
cpu.cc:106: error: ‘__m128i’ was not declared in this scope
cpu.cc:106: error: ‘q’ was not declared in this scope
cpu.cc:106: error: expected primary-expression before ‘)’ token
cpu.cc:111: error: expected `;' before ‘xmm0’
cpu.cc:112: error: ‘xmm0’ was not declared in this scope
cpu.cc:112: error: expected primary-expression before ‘)’ token
cpu.cc:112: error: ‘_mm_loadu_si128’ was not declared in this scope
cpu.cc:116: error: expected `;' before ‘xmm6’
cpu.cc:117: error: ‘xmm6’ was not declared in this scope
cpu.cc:117: error: ‘_mm_unpacklo_epi8’ was not declared in this scope
cpu.cc:118: error: ‘xmm7’ was not declared in this scope
cpu.cc:118: error: ‘_mm_unpacklo_epi16’ was not declared in this scope
cpu.cc:119: error: ‘xmm1’ was not declared in this scope
cpu.cc:119: error: ‘_mm_unpacklo_epi32’ was not declared in this scope
cpu.cc:121: error: ‘xmm2’ was not declared in this scope
cpu.cc:121: error: ‘c2’ was not declared in this scope
cpu.cc:121: error: ‘_mm_or_si128’ was not declared in this scope
cpu.cc:122: error: ‘xmm3’ was not declared in this scope
cpu.cc:122: error: ‘c3’ was not declared in this scope
cpu.cc:122: error: ‘_mm_cmpeq_epi8’ was not declared in this scope
cpu.cc:123: error: ‘xmm4’ was not declared in this scope
cpu.cc:124: error: ‘xmm5’ was not declared in this scope
cpu.cc:124: error: ‘_mm_unpackhi_epi8’ was not declared in this scope
cpu.cc:125: error: ‘_mm_subs_epi16’ was not declared in this scope
make[2]: *** [libcpu_sse2_a-cpu.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Ideas? (I do most of my work on Linux and other functions of vsearch work for me, so fixing this function on macOSX is not critical for me. You don't have to stress about this :smile: )

**Comment by torognes** [comment]
Hi @colinbrislawn, it seems like you are missing the x86intrin.h file. Either it is not installed or the compiler cannot find it.

I am looking into some possibilities for making sure that the binary distributions of vsearch works well on older versions of OS X that the one I am compiling it on (10.11.1 El Capitan). Hopefully I will release a patch later today.

**Comment by torognes** [comment]
Should be fixed in vsearch 1.8.1.

**Comment by colinbrislawn** [comment]
Thank you @torognes! I appreciate your ongoing support for my old mac. The binary for 1.8.1 works great!

I still can't build from source, but that's due to software I'm missing on my system. (Same error after I use `AC_PREREQ([2.61])`).
